project:
  type: website

website:
  title: "Influenciadores Financeiros"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
     theme: lumen
     css: styles.css
     toc: false
     html-table-processing: none


editor: visual

